# Generated by Django 4.1.7 on 2023-02-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('task', models.CharField(max_length=600)),
                ('completed', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
